# Keep your existing imports
from django.urls import path, include
from rest_framework.routers import DefaultRouter
# Import all the necessary views, including the new auth views
from .views import (
    CourseViewSet,
    LessonViewSet,
    MarkLessonCompleteView,
    UserProgressView,
    QuizViewSet,
    RegisterView,
    LoginView
)

# Your existing router setup
router = DefaultRouter()
router.register(r'courses', CourseViewSet, basename='course')
router.register(r'lessons', LessonViewSet, basename='lesson')
router.register(r'quizzes', QuizViewSet, basename='quiz')


# The API URLs are now determined automatically by the router.
urlpatterns = [
    # Add the new auth URLs at the top
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),

    # This line includes all the URLs automatically generated by the router
    path('', include(router.urls)),

    # The custom view URLs that are not part of a ViewSet
    path('lessons/<int:lesson_id>/complete/', MarkLessonCompleteView.as_view(), name='mark-lesson-complete'),
    path('progress/<int:course_id>/', UserProgressView.as_view(), name='user-course-progress'),
]
